### PR TITLE
feat: Remove holiday field from mock data

### PR DESCRIPTION
**Pull request by bistaastha**
### <samp>🤖 Generated by Copilot at f33182d</samp>

Removed the unused `tx_is_holiday_expense` property from various mock data files in the app's core module. This property was not relevant for the app's functionality and was causing confusion. This change simplifies the mock data structure and improves code readability.

### <samp>🤖 Generated by Copilot at f33182d</samp>

> _Sing, O Muse, of the swift and skillful coder_
> _Who cleansed the mock data of a needless field_
> _And thus removed the source of much disorder_
> _And made the app's functionality more clear._

### <samp>🤖 Generated by Copilot at f33182d</samp>

*  Remove `tx_is_holiday_expense` property from mock data objects as it is not used in the app ([link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-786c5a47a848fb3ddb2ed5a158da6fcd8cde95b79fd6b72976a7301c9f8c4082L109), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-786c5a47a848fb3ddb2ed5a158da6fcd8cde95b79fd6b72976a7301c9f8c4082L332), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-786c5a47a848fb3ddb2ed5a158da6fcd8cde95b79fd6b72976a7301c9f8c4082L541), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-786c5a47a848fb3ddb2ed5a158da6fcd8cde95b79fd6b72976a7301c9f8c4082L760), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-722ddf80d81ed0a6f2442904bd8c57dff8f96df71d82abeab519b18576c67ab8L100), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-722ddf80d81ed0a6f2442904bd8c57dff8f96df71d82abeab519b18576c67ab8L315), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-722ddf80d81ed0a6f2442904bd8c57dff8f96df71d82abeab519b18576c67ab8L521), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L494), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L690), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L902), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L1421), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L1623), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L1952), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L2156), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L2359), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L2562), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L2901), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L3231), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L3436), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L3641), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L4651), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L4901), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L5138), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L5406), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-56d972f354883e74d1aa98489079c2d3d173a8d3417fb7d5760cff7a26e7f992L5723), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-b7d2bafc15460129308d6d4a081d272a1dfbfd97505801d2a413a61d607e22f1L149), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-b7d2bafc15460129308d6d4a081d272a1dfbfd97505801d2a413a61d607e22f1L429), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-b7d2bafc15460129308d6d4a081d272a1dfbfd97505801d2a413a61d607e22f1L670), [link](https://github.com/fylein/fyle-mobile-app/pull/2541/files?diff=unified&w=0#diff-b7d2bafc15460129308d6d4a081d272a1dfbfd97505801d2a413a61d607e22f1L916))

## Code Coverage
Please add code coverage here

## UI Preview
Please add screenshots for UI changes

### CODE REVIEW

**Review by OmkarJ13 — APPROVED** [review]
Ig this needs to be removed from the models as well, is this done already?

**Comment by bistaastha** [comment]
@OmkarJ13 I didn't find any mentions for `tx_is_holiday_expense` in any models

**Comment by OmkarJ13** [comment]
> @OmkarJ13 I didn't find any mentions for `tx_is_holiday_expense` in any models

Can you check `expense.model.ts`?  One key is present there 
Ref: https://github.com/fylein/fyle-mobile-app/blob/85d69f09e0a5408fc6702bb31bd5e49f274a3519/src/app/core/models/expense.model.ts#L92

**Comment by bistaastha** [comment]
> Can you check expense.model.ts? One key is present there
Yes, found this. Thanks.

**Review by jayfyle — APPROVED** [review]

**Pull request merged**
