### PR TITLE
Virtual scroll in select modal

### PR DESCRIPTION
**Pull request by Dimple16**

### CODE REVIEW

**Comment by Julias0** [comment]
The scroll should include the recently selected items too - otherwise the interaction looks a bit weired

**Review by Julias0 — CHANGES_REQUESTED** [review]
The scroll should include the recently selected items too - otherwise the interaction looks a bit weired

**Comment by Dimple16** [comment]
@Julias0 the recently used is a separate list, in this case, so we would need to add 2 virtual scrolls, I tried this too, since max only 4 items can be present, the scroll doesn't have an impact as such here

**Comment by Julias0** [comment]
> @Julias0 the recently used is a separate list, in this case, so we would need to add 2 virtual scrolls, I tried this too, since max only 4 items can be present, the scroll doesn't have an impact as such here

Cant we concatenate both the lists so that it feels like they are part of the same?

**Review by Julias0 — CHANGES_REQUESTED** [review]
Asked questions on slack

**Review by Julias0 — CHANGES_REQUESTED** [review]
This implementation needs to be changed

**Pull request closed without merging**
